name: Build and scan container image

on:
  workflow_dispatch:

jobs:
  build-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write
  
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: rajmor/alpine:latest
      
      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations,quickview
          image: rajmor/alpine:latest
          sarif-file: sarif.output.json
          summary: true
      
      - name: Upload SARIF result
        id: upload-sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif.output.json
      
      - uses: actions/upload-artifact@v4
        with:
          name: sarif-report
          path: ./sarif.output.json
